### PR TITLE
Add support for mutable-content flag (iOS 10)

### PR DESCRIPTION
**Pull request by mat**
This adds support for the new `mutable-content` flag in iOS 10:
https://developer.apple.com/videos/play/wwdc2016/707/?time=2087

We've been running this patch in production for more than a week now without any problems.

### CODE REVIEW

**Comment by stevenharman** [comment]
Could you also document this new option in the `README`?

**Comment by mat** [comment]
Good point, done!

**Comment by stevenharman** [comment]
I just published version `0.7.0` which includes the `mutable-content` flag. Thanks!

**Comment by mat** [comment]
Great, thanks, now we can stop using our own fork again 🎉

**Pull request merged**
